chatbot/urls.py
from django.urls import path
from . import views


app_name = "chatbot"
urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.home, name='home'),
    path('about/', views.about, name="about"),
    path('openai-bot/', views.openai_bot, name="openai"),
    path('gemini-bot/', views.gemini_bot, name="gemini"),
    path('input/',views.input_view, name='input'),
]

model_mix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
]

chatbot/models.py
from django.db import models

# Create your models here.

chatbot/forms.py
# forms.py
from django import forms

class InputForm(forms.Form):
    user_input = forms.CharField(
        label='Prompt here..', 
        max_length=100, 
        widget=forms.TextInput(attrs={'class': 'large-input'})
    )

chatbot/views.py
from django.shortcuts import render, HttpResponse, render
from .forms import InputForm
from openai._client import OpenAI
from django.conf import settings
from dotenv import load_dotenv
import textwrap
import os
import google.generativeai as genai
from IPython.display import Markdown

# Create your views here.

def home(request):
    return render(request, "chatbot/home.html")

def about(request):
    return render(request, "chatbot/about.html")


load_dotenv()
client = OpenAI(api_key=settings.OPENAI_API_KEY)

def generate_message(system_input, user_input):
    message = [{
        'role':'system',
        'content':system_input},
        {'role':'user',
         'content':user_input
    }]
    return message

def generate_response(system_input, user_input, model='gpt-3.5-turbo', temperature = 0.2):
    
    messages = generate_message(system_input, user_input)

    response = client.chat.completions.create(model=model,
                                 messages = messages,
                                 temperature = temperature)
    
    return response.choices[0].message.content

def openai_bot(request):    
    response_text = None

    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            user_input = form.cleaned_data['user_input']
            print("user_input",user_input)
            system_input = "You are a generalist who is expert in all the fields.Respond to user input to the best of your ability. You should sound friendly.\
                with every question user ask, chellange them to ask more tougher question and reply in short and crisp answer.\
                    If you do not know the answer, than say sorry in a funny way like you do not mean it and it's okay to not know some of the things.\
                        At the end, ask user if they need more assistance."


            response_text = generate_response(system_input, user_input)
            
    else:
        form = InputForm()

    return render(request, 'chatbot/openai.html', {'form': form, 'response': response_text})



# generating google gemini response
GOOGLE_API_KEY = settings.GOOGLE_API_KEY

genai.configure(api_key=GOOGLE_API_KEY)



def get_resposne_google(user_input):
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(user_input)
    return (response.text)

def gemini_bot(request):

    resposnse_text = None

    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            user_input = form.cleaned_data['user_input']
            print("user_input",user_input)

            resposnse_text = get_resposne_google(user_input)

    else:
        form = InputForm()

    return render(request, "chatbot/gemini.html", {'form': form, 'response': resposnse_text})




def input_view(request):
    user_input = ''
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            user_input = form.cleaned_data['user_input']
            form = InputForm() 
    else:
        form = InputForm()

    return render(request, 'chatbot/input.html', {'form': form, 'user_input': user_input})

chatbot/templates/chatbot/about.html
{% extends "chatbot/base.html" %}

{% block content%}
<div class="container-fluid border border-black mt-5 text-center">
    this is about
</div>

{%endblock%}

chatbot/templates/chatbot/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title> Ankit's WebApp | </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/project_image/css/style.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    {% block head %}{% endblock head %} <!-- Head Block -->

    <style>
        /* Additional styling if needed */
        body { padding-top: 0px; } /* Adjust this value if your navbar is a different height */
    </style>
</head>
<body>

{% block navbar %} <!-- Navbar Block -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <a class="navbar-brand" href="../">Ankit's WebApp</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/dashboard">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "chatbot:about"%}">About</a>
            </li>            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Products
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url "chatbot:openai"%}">OpenAI Chatbot</a>
                    <a class="dropdown-item" href="{% url "chatbot:gemini"%}">Google's Gemini</a>
                    <a class="dropdown-item" href="#">Upcoming...</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/dashboard#contact">Contact Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "chatbot:input"%}">Input View</a>
            </li> 
        </ul>
    </div>
</nav>
{% endblock navbar %}
    
{% block content %} <!-- Main Content Block -->
{% endblock content %}

{% block footer %} <!-- Footer Block -->
<!-- Optional Footer Content Here -->
<div class="text-center mt-5 fully-transparent-container">
    This website was developed by Ankit
</div>
{% endblock footer %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

chatbot/templates/chatbot/gemini.html
{% extends "chatbot/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid mt-5 text-center">
    <div class="row-12">
        <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded p-3 mb-2 bg-light">
            <div class="header">Welcome to the Google's Gemini based Chatbot of this WebApp.</div>
        </div>
    </div>

    <div class="centered-container">
        <h1 class="heading">Ask me Anything..!</h1>
        <div class="form-container">
            <form method="POST" id="chat-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Generate Response</button>
            </form>
        </div>

        {% if response %}
        <div class="form-container my-2">
            <div id="response">
                <p>Bot's response: {{ response }}</p>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

chatbot/templates/chatbot/home.html
{% extends "chatbot/base.html" %}
{% load static %}


{% block content%}
<div class="container-fluid mt-5 text-center">
    <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded p-3 mb-2 bg-light">
        <div class="header"> Welcome to the homepage of this WebApp. </h5>
    </div>
    
</div>




{%endblock%}

chatbot/templates/chatbot/input.html
{% extends "chatbot/base.html" %}

<!-- input.html -->
{% block content%}
<body>
    <div class="center-container">
        <div class="form-container">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="success">Submit</button>
            </form>
            {% if user_input %}
                <p>You prompted: {{ user_input }}</p>
            {% endif %}
        </div>
    </div>
</body>

{% endblock %}

chatbot/templates/chatbot/openai.html
{% extends "chatbot/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid mt-5 text-center">
    <div class="row-12">
        <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded p-3 mb-2 bg-light">
            <div class="header">Welcome to the OpenAI based Chatbot of this WebApp.</div>
        </div>
    </div>

    <div class="centered-container">
        <h1 class="heading">Ask me Anything..!</h1>
        <div class="form-container">
            <form method="POST" id="chat-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Generate Response</button>
            </form>
        </div>

        {% if response %}
        <div class="form-container my-2">
            <div id="response">
                <p>Bot's response: {{ response }}</p>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}